"""Remove password login tracking columns

Revision ID: f1a2b3c4d5e6
Revises: c966f8ce2d73
Create Date: 2025-11-16 15:35:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = 'c966f8ce2d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove password login tracking columns that are no longer needed (OAuth-only)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('account_locked_until')
        batch_op.drop_column('last_failed_login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore columns if we need to rollback
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_failed_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('account_locked_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.INTEGER(), autoincrement=False, nullable=False, server_default='0'))
    # ### end Alembic commands ###
